PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?term ?value
WHERE {
  ?term rdfs:label ?value .
  FILTER (REGEX(?value, "http[s]?[:]"))
  FILTER(isIRI(?term) && (STRSTARTS(str(?term), "http://flybase.org/reports/") || STRSTARTS(str(?term), "https://www.ncbi.nlm.nih.gov/bioproject/") || STRSTARTS(str(?term), "https://www.ncbi.nlm.nih.gov/sra/") || STRSTARTS(str(?term), "https://www.ncbi.nlm.nih.gov/biosample/")))
}

